---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604

script:
  - ./tests/geerlingguy.test/ansible-role-test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
